//AHORCADO Y SOPA DE LETRAS
export const words = [
  'rails',
  'angularJS',
  'bootstrap',
  'ruby',
  'javascript',
  'authentication',
  'function',
  'array',
  'object',
  'sublime',
  'github',
  'agile',
  'route',
  'database',
  'model',
  'view',
  'controller',
  'terminal',
  'array',
  'data',
  'inheritance',
  'heroku',
  'scope',
  'closure',
  'algorithm',
  'analog',
  'app',
  'application',
  'backup',
  'bandwidth',
  'binary',
  'bit',
  'bitmap',
  'browser',
  'buffer',
  'bug',
  'bus',
  'byte',
  'cache',
  'captcha',
  'ram',
  'rom',
  'client',
  'cloud',
  'command',
  'compiler',
  'compress',
  'program',
  'cookie',
  'cpu',
  'cybercrime',
  'dashboard',
  'debug',
  'decompress',
  'dns',
  'domain',
  'emailemoticon',
  'encrypt',
  'firewall',
  'firmware',
  'flash',
  'gigabyte',
  'hacker',
  'hardware',
  'host',
  'html',
  'hyperlink',
  'hypertext',
  'integer',
  'interface',
  'java',
  'kernel',
  'keykeyboard',
  'keyword',
  'link',
  'linux',
  'log',
  'macintosh',
  'malware',
  'memory',
  'motherboard',
  'net',
  'network',
  'system',
  'password',
  'path',
  'phishing',
  'piracy',
  'pirate',
  'platform',
  'popup',
  'privacy',
  'process',
  'program',
  'protocol',
  'queue',
  'query',
  'reboot',
  'resolution',
  'root',
  'router',
  'runtime',
  'script',
  'scroll',
  'security',
  'server',
  'shell',
  'spam',
  'spyware',
  'syntax',
  'tag',
  'teminal',
  'template',
  'terabyte',
  'thread',
  'trojan',
  'unix',
  'url',
  'virus',
  'web',
  'website',
  'process',
  'xml',
  'zip',
];

//ahorcado:
export const missesAllowed = 5;
export const timeAhorcado = 30;

//sopa de letras palabras:
export const wordsBySoup = 15;
export const timeSoup = 60;
export const bonusGuessedWord = 5;

//mayoromenor
export const cards = [
  1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11,
  12, 13, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 1, 2, 3, 4, 5, 6, 7, 8, 9,
  10, 11, 12, 13,
];

//Preguntados
export const scores = [
  { score: 50, earned: false, current: false },
  { score: 100, earned: false, current: false },
  { score: 200, earned: false, current: false },
  { score: 400, earned: false, current: false },
  { score: 800, earned: false, current: false },
  { score: 1500, earned: false, current: false },
  { score: 3000, earned: false, current: false },
  { score: 6000, earned: false, current: false },
  { score: 10000, earned: false, current: false },
];
